// WORK WITH FORM
export const ACTION_CHANGE_PHONE = 'ACTION_CHANGE_PHONE';
export const ACTION_CHANGE_NAME = 'ACTION_CHANGE_NAME';

// MODALS
export const ACTION_SHOW_MODAL_EDIT = 'ACTION_SHOW_MODAL_EDIT';
export const ACTION_SHOW_MODAL_NEW = 'ACTION_SHOW_MODAL_NEW';

// CRUD
export const ACTION_GET = 'ACTION_GET';